// AUTO-GENERATED from data/*.json by tools/convert.py — do not hand-edit.
// Embedded fallback so the app loads when opened directly (file://).
window.GAME_DATA = {
  "heroes": [
    {
      "id": "paladin",
      "name": "Paladin",
      "abilities": "2☼: Give +1☼ to an ally hero's roll. Lose 1 life.\n\n3☼: Draw an extra card.\n\nOnly Lose -3 life if 2 or less spaces away from the monster in line of sight.\n\nRegain 2 life if you end your turn next to an ally.\n\nDoes +1 to minions.",
      "objectiveAbilities": "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 6☼: Move next to an ally hero who is alive. Lose 2 life.\n\n7◆: Gain ☼ Bonus\n7◆: Allies 1 space away get +2 to any roll.\n\n8◆:",
      "raw": [
        "4",
        "",
        "2☼: Give +1☼ to an ally hero's roll. Lose 1 life.\n\n3☼: Draw an extra card.\n\nOnly Lose -3 life if 2 or less spaces away from the monster in line of sight.\n\nRegain 2 life if you end your turn next to an ally.\n\nDoes +1 to minions.",
        "1",
        "4",
        "6",
        "RED",
        "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 6☼: Move next to an ally hero who is alive. Lose 2 life.\n\n7◆: Gain ☼ Bonus\n7◆: Allies 1 space away get +2 to any roll.\n\n8◆:",
        "",
        "12",
        "",
        "Paladin",
        "RED"
      ],
      "color": "RED",
      "pair": "red",
      "cardFace": "front",
      "art": "players/red2.jpg",
      "stats": {
        "actionDie": 4,
        "movementDie": 6,
        "life": 12,
        "bonusDice": [
          4
        ],
        "specialDie": null
      }
    },
    {
      "id": "barbarian",
      "name": "Barbarian",
      "abilities": "4☼: During your next movement, kill all minions who would be in range for combat while moving\n\nOnly Lose -3 life if 2 or less spaces away from the monster in line of sight.\n\nIf caught by a monster in a building, lose -2 life and escape the building.\n\nDefeating a minion restores +2 life.\n\nDoes +2 to minions and Minions do -1 to hero.",
      "objectiveAbilities": "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 3☼: Move all minions that are 6+X☼ spaces away next to you. Engage combat. use any extra ☼ for X.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
      "raw": [
        "4",
        "",
        "4☼: During your next movement, kill all minions who would be in range for combat while moving\n\nOnly Lose -3 life if 2 or less spaces away from the monster in line of sight.\n\nIf caught by a monster in a building, lose -2 life and escape the building.\n\nDefeating a minion restores +2 life.\n\nDoes +2 to minions and Minions do -1 to hero.",
        "",
        "4",
        "6",
        "RED",
        "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 3☼: Move all minions that are 6+X☼ spaces away next to you. Engage combat. use any extra ☼ for X.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
        "",
        "12",
        "",
        "Barbarian",
        ""
      ],
      "color": "RED",
      "pair": "red",
      "cardFace": "back",
      "art": "players/red1.jpg",
      "stats": {
        "actionDie": 4,
        "movementDie": 6,
        "life": 12,
        "bonusDice": [
          4
        ],
        "specialDie": null
      }
    },
    {
      "id": "hunter",
      "name": "Hunter",
      "abilities": "3☼: Summon your pet. Can only have 1 summoned at a time.\n\n2☼: Pet performs an action.\n\nPet can fly over obstacles(not walls).\nMovement rolls are shared between the pet and hero. NOT bonus Dice.\n\nPet dies in any combat with monster.",
      "objectiveAbilities": "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 6☼: Summon a second pet.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
      "raw": [
        "4",
        "",
        "3☼: Summon your pet. Can only have 1 summoned at a time.\n\n2☼: Pet performs an action.\n\nPet can fly over obstacles(not walls).\nMovement rolls are shared between the pet and hero. NOT bonus Dice.\n\nPet dies in any combat with monster.",
        "1",
        "6",
        "12",
        "YELLOW",
        "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 6☼: Summon a second pet.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
        "",
        "20",
        "",
        "Hunter",
        "YELLOW"
      ],
      "color": "YELLOW",
      "pair": "yellow",
      "cardFace": "front",
      "art": "players/yellow1.jpg",
      "stats": {
        "actionDie": 6,
        "movementDie": 12,
        "life": 20,
        "bonusDice": [
          4
        ],
        "specialDie": null
      }
    },
    {
      "id": "scout",
      "name": "Scout",
      "abilities": "1☼: Increase movement roll by 2.\n\n5֍: Perform an action.\n\nOnly lose -3 life if 7 or more spaces away from the monster in line of sight.\n\n\n\nRoll a 4 with ☼ to avoid death when caught by a monster in a building.",
      "objectiveAbilities": "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 4☼: Move to any wall in line of sight. End Turn.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
      "raw": [
        "4",
        "",
        "1☼: Increase movement roll by 2.\n\n5֍: Perform an action.\n\nOnly lose -3 life if 7 or more spaces away from the monster in line of sight.\n\n\n\nRoll a 4 with ☼ to avoid death when caught by a monster in a building.",
        "",
        "6",
        "12",
        "YELLOW",
        "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 4☼: Move to any wall in line of sight. End Turn.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
        "",
        "20",
        "",
        "Scout",
        ""
      ],
      "color": "YELLOW",
      "pair": "yellow",
      "cardFace": "back",
      "art": "players/yellow2.jpg",
      "stats": {
        "actionDie": 6,
        "movementDie": 12,
        "life": 20,
        "bonusDice": [
          4
        ],
        "specialDie": null
      }
    },
    {
      "id": "wizard",
      "name": "Wizard",
      "abilities": "2☼: Reroll any dice this turn.\n\n4☼: Draw an extra card\n\nMay discard a card to draw another card.\n\nHas -2 to every roll in combat. Always goes second in combat.",
      "objectiveAbilities": "2,5,6◇: Draw a card\n\n3◇: Relocate 1 door\n\n4◆: Gain ֍ Bonus\n\n5◆: 6☼: Trade places with any object.\n5◇: Relocate 1 door\n\n7◆: Gain ☼ Bonus",
      "raw": [
        "6",
        "",
        "2☼: Reroll any dice this turn.\n\n4☼: Draw an extra card\n\nMay discard a card to draw another card.\n\nHas -2 to every roll in combat. Always goes second in combat.",
        "1",
        "4",
        "4",
        "BLUE",
        "2,5,6◇: Draw a card\n\n3◇: Relocate 1 door\n\n4◆: Gain ֍ Bonus\n\n5◆: 6☼: Trade places with any object.\n5◇: Relocate 1 door\n\n7◆: Gain ☼ Bonus",
        "4",
        "4",
        "",
        "Wizard",
        "BLUE"
      ],
      "color": "BLUE",
      "pair": "blue",
      "cardFace": "front",
      "art": "players/blue2.jpg",
      "stats": {
        "actionDie": 4,
        "movementDie": 4,
        "life": 4,
        "bonusDice": [
          6
        ],
        "specialDie": 4
      }
    },
    {
      "id": "enchantress",
      "name": "Enchantress",
      "abilities": "4☼: Walk through a wall.\n\n5☼: Move a monster or ally 1 space.\n\nMay discard a card to draw another card.\n\nCan only use 1 dice for combat and escaping.\n\n\nHas -1 to every roll in combat. Always goes second in combat.",
      "objectiveAbilities": "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n4◆: 6☼: Use any ally card on any hero.\n\n5◆: 7☼: Use an action anywhere.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
      "raw": [
        "4",
        "4",
        "4☼: Walk through a wall.\n\n5☼: Move a monster or ally 1 space.\n\nMay discard a card to draw another card.\n\nCan only use 1 dice for combat and escaping.\n\n\nHas -1 to every roll in combat. Always goes second in combat.",
        "",
        "4",
        "4",
        "BLUE",
        "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n4◆: 6☼: Use any ally card on any hero.\n\n5◆: 7☼: Use an action anywhere.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
        "",
        "6",
        "",
        "Enchantress",
        ""
      ],
      "color": "BLUE",
      "pair": "blue",
      "cardFace": "back",
      "art": "players/blue1.jpg",
      "stats": {
        "actionDie": 4,
        "movementDie": 4,
        "life": 6,
        "bonusDice": [
          4,
          4
        ],
        "specialDie": null
      }
    },
    {
      "id": "thief",
      "name": "Thief",
      "abilities": "1☼ and 2֍: Use an action 2 spaces away.\n\n5☼: Use an ally hero's card.\n\nRolls with the D10 can be used to move diagonally a space.\n\n Has -4 to all combat and escape rolls.\n\n\nMay initiate combat through a wall.",
      "objectiveAbilities": "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 6☼: Can not be targeted or seen until next turn.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
      "raw": [
        "8",
        "",
        "1☼ and 2֍: Use an action 2 spaces away.\n\n5☼: Use an ally hero's card.\n\nRolls with the D10 can be used to move diagonally a space.\n\n Has -4 to all combat and escape rolls.\n\n\nMay initiate combat through a wall.",
        "1",
        "4",
        "10",
        "GREEN",
        "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 6☼: Can not be targeted or seen until next turn.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
        "4",
        "10",
        "",
        "Thief",
        "GREEN"
      ],
      "color": "GREEN",
      "pair": "green",
      "cardFace": "front",
      "art": "players/green1.jpg",
      "stats": {
        "actionDie": 4,
        "movementDie": 10,
        "life": 10,
        "bonusDice": [
          8
        ],
        "specialDie": 4
      }
    },
    {
      "id": "ranger",
      "name": "Ranger",
      "abilities": "2☼: -2 to a minion 4 spaces away.\n\n3☼ and 4֍: Move an Objective 1 space.\n\nRolls with the D10 can be used to move diagonally a space.\n\nCan initiate combat 3 spaces away.\n\nHas +1 in combat, if more than 1 space away.",
      "objectiveAbilities": "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 4☼: Reroll any ֍ dice.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
      "raw": [
        "4",
        "",
        "2☼: -2 to a minion 4 spaces away.\n\n3☼ and 4֍: Move an Objective 1 space.\n\nRolls with the D10 can be used to move diagonally a space.\n\nCan initiate combat 3 spaces away.\n\nHas +1 in combat, if more than 1 space away.",
        "",
        "4",
        "10",
        "GREEN",
        "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 4☼: Reroll any ֍ dice.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
        "8",
        "10",
        "",
        "Ranger",
        ""
      ],
      "color": "GREEN",
      "pair": "green",
      "cardFace": "back",
      "art": "players/green2.jpg",
      "stats": {
        "actionDie": 4,
        "movementDie": 10,
        "life": 10,
        "bonusDice": [
          4
        ],
        "specialDie": 8
      }
    },
    {
      "id": "druid",
      "name": "Druid",
      "abilities": "3☼: Transform. Persists until cast again. Can be used multiple times per turn.\n\n4☼: Transform an ally for this turn.\n\nTURTLE: +3☼ and -4֍\nCHEETAH: +4֍ and -3☼\nBEAR: +2 in combat roll. take -1 from minions.\nDEER: Restore +2 life to any hero for 1☼, Takes +4 from attacks while in this form.\n\nHas -3 to all combat and escape rolls. Always goes second in combat.",
      "objectiveAbilities": "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n4◆: Rolls with the D10 can be used to move diagonally a space.\n\n5◆: 3☼: Draw an extra card.\n\n7◆: Gain ☼ Bonus.",
      "raw": [
        "6",
        "",
        "3☼: Transform. Persists until cast again. Can be used multiple times per turn.\n\n4☼: Transform an ally for this turn.\n\nTURTLE: +3☼ and -4֍\nCHEETAH: +4֍ and -3☼\nBEAR: +2 in combat roll. take -1 from minions.\nDEER: Restore +2 life to any hero for 1☼, Takes +4 from attacks while in this form.\n\nHas -3 to all combat and escape rolls. Always goes second in combat.",
        "1",
        "4",
        "10",
        "PURPLE",
        "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n4◆: Rolls with the D10 can be used to move diagonally a space.\n\n5◆: 3☼: Draw an extra card.\n\n7◆: Gain ☼ Bonus.",
        "",
        "8",
        "",
        "Druid",
        "PURPLE"
      ],
      "color": "PURPLE",
      "pair": "purple",
      "cardFace": "front",
      "art": "players/purple2.jpg",
      "stats": {
        "actionDie": 4,
        "movementDie": 10,
        "life": 8,
        "bonusDice": [
          6
        ],
        "specialDie": null
      }
    },
    {
      "id": "cleric",
      "name": "Cleric",
      "abilities": "12☼: Revive any hero to half health. End both heroes turns.\n\n4☼: Restore +3 life to any living hero.\n\nBoth Dice count towards actions OR Movements. Excludes Bonus Dice. Can only use 1 dice for combat and escaping.\n\n\nHas -4 to all combat and escape rolls. Always goes second in combat.",
      "objectiveAbilities": "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 3☼: Give +2☼ to an ally hero's roll. Lose 2 life.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
      "raw": [
        "6",
        "8",
        "12☼: Revive any hero to half health. End both heroes turns.\n\n4☼: Restore +3 life to any living hero.\n\nBoth Dice count towards actions OR Movements. Excludes Bonus Dice. Can only use 1 dice for combat and escaping.\n\n\nHas -4 to all combat and escape rolls. Always goes second in combat.",
        "",
        "4",
        "6",
        "PURPLE",
        "2,5,6◇: Draw a card\n\n4◆: Gain ֍ Bonus\n\n5◆: 3☼: Give +2☼ to an ally hero's roll. Lose 2 life.\n\n7◆: Gain ☼ Bonus\n\n8◆:",
        "6",
        "8",
        "",
        "Cleric",
        ""
      ],
      "color": "PURPLE",
      "pair": "purple",
      "cardFace": "back",
      "art": "players/purple1.jpg",
      "stats": {
        "actionDie": 4,
        "movementDie": 6,
        "life": 8,
        "bonusDice": [
          6,
          8
        ],
        "specialDie": 6
      }
    }
  ],
  "monsters": [
    {
      "id": "maraurnzol",
      "name": "Maraurn'Zol",
      "abilities": "x◆: Take an extra movement turn for every 4 objectives taken.\n2◆: Attack all heroes 1 space away.\n4◆: Attack all heroes 2 spaces away.\n7◆: Attack all heroes 3 spaces away.\nAttacking deals ☼ to heroes life total.\n\nMaraurn'Zol attacks around her through all objects. Allow heroes attacked to escape with a 2☼ or higher\n\nLine of sight is limited to 6 spaces.",
      "objectiveAbilities": "6◇: Add a clone of Maraun'Zol. The clone takes it's turn after Maraun'Zol.\n\n9◇: Immediately take your turn. ALL random. No line of sight damage.",
      "raw": [
        "",
        "6",
        "x◆: Take an extra movement turn for every 4 objectives taken.\n2◆: Attack all heroes 1 space away.\n4◆: Attack all heroes 2 spaces away.\n7◆: Attack all heroes 3 spaces away.\nAttacking deals ☼ to heroes life total.\n\nMaraurn'Zol attacks around her through all objects. Allow heroes attacked to escape with a 2☼ or higher\n\nLine of sight is limited to 6 spaces.",
        "1",
        "",
        "",
        "MONSTER",
        "6◇: Add a clone of Maraun'Zol. The clone takes it's turn after Maraun'Zol.\n\n9◇: Immediately take your turn. ALL random. No line of sight damage.",
        "",
        "",
        "Fire",
        "Maraurn'Zol",
        "MONSTER"
      ],
      "element": "Fire",
      "art": "players/bad5.jpg",
      "stats": {
        "monsterDie": 6,
        "actionDie": null,
        "movementDie": null,
        "specialDie": null
      }
    },
    {
      "id": "wyhtthetrickster",
      "name": "Wyht, the Trickster",
      "abilities": "x◆: Take an extra movement turn for every 3 objectives taken.\n4◆: Randomly relocate any objective.\n6◆: Make a hero discard a card (1st turn only)\n9◆: Make a hero discard a card (2nd turn only)\n\nWyht Draws an extra card when she draws cards.",
      "objectiveAbilities": "1◇: Add 1 more objective. ALL random.\n\n6◇: Add 1 more objective. randomly\n\n10◇: Choose a hero, they die.",
      "raw": [
        "",
        "6",
        "x◆: Take an extra movement turn for every 3 objectives taken.\n4◆: Randomly relocate any objective.\n6◆: Make a hero discard a card (1st turn only)\n9◆: Make a hero discard a card (2nd turn only)\n\nWyht Draws an extra card when she draws cards.",
        "",
        "",
        "",
        "MONSTER",
        "1◇: Add 1 more objective. ALL random.\n\n6◇: Add 1 more objective. randomly\n\n10◇: Choose a hero, they die.",
        "",
        "",
        "Mind",
        "Wyht, the Trickster",
        ""
      ],
      "element": "Mind",
      "art": "players/bad1.jpg",
      "stats": {
        "monsterDie": 6,
        "actionDie": null,
        "movementDie": null,
        "specialDie": null
      }
    },
    {
      "id": "ghathag",
      "name": "Ghathag",
      "abilities": "x◆: Take an extra movement turn for every 4 objectives taken.\n2◆: Stalk 3 spaces.\n3◆:Place a 2 life 2x1 obstacle\n4◆: Stalk 3 more spaces.\n6◆: Stalk 3 more spaces.\n\nAllow heroes to escape with a 2☼ or higher if seen while moving.\nGhathag can not enter doors.\n\nLine of Sight is limited to 4 spaces, and 1 when Stalking.",
      "objectiveAbilities": "3◇: Place 2 obstacles\n\n4◆: Obstacles have +2 life.\n\n5◇: Place 2 obstacles.\n\n7◆: Obstacles have +2 life.\n\n9◇: Turn all obstacles into a minion(Roll each)",
      "raw": [
        "",
        "6",
        "x◆: Take an extra movement turn for every 4 objectives taken.\n2◆: Stalk 3 spaces.\n3◆:Place a 2 life 2x1 obstacle\n4◆: Stalk 3 more spaces.\n6◆: Stalk 3 more spaces.\n\nAllow heroes to escape with a 2☼ or higher if seen while moving.\nGhathag can not enter doors.\n\nLine of Sight is limited to 4 spaces, and 1 when Stalking.",
        "",
        "",
        "",
        "MONSTER",
        "3◇: Place 2 obstacles\n\n4◆: Obstacles have +2 life.\n\n5◇: Place 2 obstacles.\n\n7◆: Obstacles have +2 life.\n\n9◇: Turn all obstacles into a minion(Roll each)",
        "",
        "",
        "Claw",
        "Ghathag",
        ""
      ],
      "element": "Claw",
      "art": "players/bad2.jpg",
      "stats": {
        "monsterDie": 6,
        "actionDie": null,
        "movementDie": null,
        "specialDie": null
      }
    },
    {
      "id": "thefog",
      "name": "The Fog",
      "abilities": "1◆: Attack all heroes 1 space away.\n4◆: Attack all heroes 2 spaces away.\n8◆: Attack all heroes 3 spaces away.\nAttacking deals ☼ to heroes life total.\n\nThe Fog moves with a D20 instead of randomly. add +2 to movement rolls.\n\nIf a hero is attacked inside a building. Allow heroes to escape with a 2☼ or higher.\n\nLine of sight is limited to 6 spaces.",
      "objectiveAbilities": "2◆:Can see heroes through all objects.\n\n2◆: Add a D4 to movement rolls.\n\n4◆: Add a D4 to movement rolls.\n\n9◇: Kill up to any 2 heroes that are not in a building.",
      "raw": [
        "",
        "6",
        "1◆: Attack all heroes 1 space away.\n4◆: Attack all heroes 2 spaces away.\n8◆: Attack all heroes 3 spaces away.\nAttacking deals ☼ to heroes life total.\n\nThe Fog moves with a D20 instead of randomly. add +2 to movement rolls.\n\nIf a hero is attacked inside a building. Allow heroes to escape with a 2☼ or higher.\n\nLine of sight is limited to 6 spaces.",
        "",
        "4",
        "4",
        "MONSTER",
        "2◆:Can see heroes through all objects.\n\n2◆: Add a D4 to movement rolls.\n\n4◆: Add a D4 to movement rolls.\n\n9◇: Kill up to any 2 heroes that are not in a building.",
        "20",
        "",
        "Smoke",
        "The Fog",
        ""
      ],
      "element": "Smoke",
      "art": "players/bad4.jpg",
      "stats": {
        "monsterDie": 6,
        "actionDie": 4,
        "movementDie": 4,
        "specialDie": 20
      }
    },
    {
      "id": "oblex",
      "name": "Oblex",
      "abilities": "1◆: Summon X/2◆ minions (round up)....\n3◆: Or give +1 to a minion\n5◆: All Minions can move 2 spaces each turn.\n\nOblex does not move extra times per objective collected.\n\nOblex can trade places with any minion after moving. Allow heroes seen to escape with a 3☼ or higher.",
      "objectiveAbilities": "1◇: Summon 2 minions.\n3◇: Summon 3 minions.\n\n4◆: minion combat is +1\n6◆: minion range is +1\n\n5◇: Summon 4 minions.\n7◆: minion combat is +1\n\n9◇: Double the number of minions.",
      "raw": [
        "6",
        "",
        "1◆: Summon X/2◆ minions (round up)....\n3◆: Or give +1 to a minion\n5◆: All Minions can move 2 spaces each turn.\n\nOblex does not move extra times per objective collected.\n\nOblex can trade places with any minion after moving. Allow heroes seen to escape with a 3☼ or higher.",
        "",
        "",
        "",
        "MONSTER",
        "1◇: Summon 2 minions.\n3◇: Summon 3 minions.\n\n4◆: minion combat is +1\n6◆: minion range is +1\n\n5◇: Summon 4 minions.\n7◆: minion combat is +1\n\n9◇: Double the number of minions.",
        "",
        "",
        "Flesh",
        "Oblex",
        ""
      ],
      "element": "Flesh",
      "art": "players/bad3.jpg",
      "stats": {
        "monsterDie": null,
        "actionDie": null,
        "movementDie": null,
        "specialDie": null
      }
    }
  ],
  "cards": [
    {
      "id": 268,
      "name": "Surprise Attack",
      "deck": "Black",
      "side": "monster",
      "timing": "draw",
      "copies": 10,
      "cost": "0",
      "text": "Choose the number and randomize\nthe letter for your next movement.\n\nThis can only be played instantly at the beginning of your turn.\n\nCan't be used on the turn it is drawn.",
      "art": "cards/surprise.png",
      "raw": [
        "268",
        "draw",
        "1",
        "0",
        "0",
        "Surprise Attack",
        "0",
        "Black",
        "1",
        "0",
        "",
        "10",
        "Choose the number and randomize\nthe letter for your next movement.\n\nThis can only be played instantly at the beginning of your turn.\n\nCan't be used on the turn it is drawn.",
        "0"
      ]
    },
    {
      "id": 269,
      "name": "Summon X Minions",
      "deck": "Black",
      "side": "monster",
      "timing": "draw",
      "copies": 10,
      "cost": "X☼",
      "text": "Randomly summon X Minions",
      "art": "cards/summonX.png",
      "raw": [
        "269",
        "draw",
        "1",
        "0",
        "0",
        "Summon X Minions",
        "0",
        "Black",
        "1",
        "0",
        "",
        "10",
        "Randomly summon X Minions",
        "X☼"
      ]
    },
    {
      "id": 284,
      "name": "Summon 1 Minion",
      "deck": "Black",
      "side": "monster",
      "timing": "draw",
      "copies": 15,
      "cost": "0",
      "text": "Randomly summon 1 Minion",
      "art": "cards/summon.png",
      "raw": [
        "284",
        "draw",
        "1",
        "0",
        "0",
        "Summon 1 Minion",
        "0",
        "Black",
        "1",
        "0",
        "",
        "15",
        "Randomly summon 1 Minion",
        "0"
      ]
    },
    {
      "id": 77,
      "name": "Lock and Key",
      "deck": "Black",
      "side": "monster",
      "timing": "draw",
      "copies": 3,
      "cost": "0",
      "text": "Choose an entrance to a building and place a lock on it. \nRandomly place a key on the map.▲\n\nHeroes must collect the key and use it on the locked door to open it. The hero who collects the key must use an action to unlock the door.\n\nIf a hero dies with a collected key, they drop the\n              Key beside them. Reroll the cost.",
      "art": "cards/doors.png",
      "raw": [
        "77",
        "draw",
        "1",
        "0",
        "0",
        "Lock and Key",
        "0",
        "Black",
        "1",
        "0",
        "",
        "3",
        "Choose an entrance to a building and place a lock on it. \nRandomly place a key on the map.▲\n\nHeroes must collect the key and use it on the locked door to open it. The hero who collects the key must use an action to unlock the door.\n\nIf a hero dies with a collected key, they drop the\n              Key beside them. Reroll the cost.",
        "0"
      ]
    },
    {
      "id": 260,
      "name": "Empowered",
      "deck": "Black",
      "side": "monster",
      "timing": "draw",
      "copies": 5,
      "cost": "0",
      "text": "The monster's next turn movement can kill heroes diagonally\n\nAll other monster rules still apply",
      "art": "cards/diaginal.png",
      "raw": [
        "260",
        "draw",
        "1",
        "0",
        "0",
        "Empowered",
        "0",
        "Black",
        "1",
        "0",
        "",
        "5",
        "The monster's next turn movement can kill heroes diagonally\n\nAll other monster rules still apply",
        "0"
      ]
    },
    {
      "id": 95,
      "name": "Drowning Paralysis",
      "deck": "Black",
      "side": "monster",
      "timing": "draw",
      "copies": 5,
      "cost": "0",
      "text": "Choose a hero. They lose a turn.",
      "art": "cards/drown.png",
      "raw": [
        "95",
        "draw",
        "1",
        "0",
        "0",
        "Drowning Paralysis",
        "0",
        "Black",
        "1",
        "0",
        "",
        "5",
        "Choose a hero. They lose a turn.",
        "0"
      ]
    },
    {
      "id": 104,
      "name": "Deathly Fear",
      "deck": "Black",
      "side": "monster",
      "timing": "draw",
      "copies": 8,
      "cost": "X☼",
      "text": "Choose X heroes.\n\nThey all have -2 to their actions and -4 to movements their next turn",
      "art": "cards/necro.png",
      "raw": [
        "104",
        "draw",
        "1",
        "0",
        "0",
        "Deathly Fear",
        "0",
        "Black",
        "1",
        "0",
        "",
        "8",
        "Choose X heroes.\n\nThey all have -2 to their actions and -4 to movements their next turn",
        "X☼"
      ]
    },
    {
      "id": 113,
      "name": "Curse of Shadows",
      "deck": "Black",
      "side": "monster",
      "timing": "draw",
      "copies": 10,
      "cost": "X☼",
      "text": "Target a hero\n\nThey have -X+1 to their next action and movement rolls",
      "art": "cards/curse.png",
      "raw": [
        "113",
        "Draw",
        "1",
        "0",
        "0",
        "Curse of Shadows",
        "0",
        "Black",
        "1",
        "0",
        "",
        "10",
        "Target a hero\n\nThey have -X+1 to their next action and movement rolls",
        "X☼"
      ]
    },
    {
      "id": 132,
      "name": "Crush Forward",
      "deck": "Black",
      "side": "monster",
      "timing": "draw",
      "copies": 8,
      "cost": "X☼",
      "text": "Move a monster or minion X spaces.\n\nMovement can be divided between multiple minions and the monster.\n\nIf the monster is able to attack a hero by moving this way, allow the hero to escape by rolling a 3 action or higher",
      "art": "cards/move.png",
      "raw": [
        "132",
        "draw",
        "1",
        "0",
        "0",
        "Crush Forward",
        "0",
        "Black",
        "1",
        "0",
        "",
        "8",
        "Move a monster or minion X spaces.\n\nMovement can be divided between multiple minions and the monster.\n\nIf the monster is able to attack a hero by moving this way, allow the hero to escape by rolling a 3 action or higher",
        "X☼"
      ]
    },
    {
      "id": 142,
      "name": "Creeping Death",
      "deck": "Black",
      "side": "monster",
      "timing": "draw",
      "copies": 10,
      "cost": "X☼",
      "text": "Move any minion X spaces.\n\nMovement can be divided between multiple minions.",
      "art": "cards/minmove.png",
      "raw": [
        "142",
        "draw",
        "1",
        "0",
        "0",
        "Creeping Death",
        "0",
        "Black",
        "1",
        "0",
        "",
        "10",
        "Move any minion X spaces.\n\nMovement can be divided between multiple minions.",
        "X☼"
      ]
    },
    {
      "id": 151,
      "name": "SpellBook +2",
      "deck": "White",
      "side": "hero",
      "timing": "hand",
      "copies": 10,
      "cost": "0",
      "text": "Increase your next action roll by +2 for one turn only.",
      "art": "cards/spell2.png",
      "raw": [
        "151",
        "hand",
        "1",
        "0",
        "0",
        "SpellBook +2",
        "0",
        "White",
        "0",
        "0",
        "",
        "10",
        "Increase your next action roll by +2 for one turn only.",
        "0"
      ]
    },
    {
      "id": 162,
      "name": "SpellBook +1",
      "deck": "White",
      "side": "hero",
      "timing": "draw",
      "copies": 10,
      "cost": "0",
      "text": "Increase your next action roll by +1 for one turn only",
      "art": "cards/spell1.png",
      "raw": [
        "162",
        "draw",
        "1",
        "1",
        "0",
        "SpellBook +1",
        "0",
        "White",
        "0",
        "0",
        "",
        "10",
        "Increase your next action roll by +1 for one turn only",
        "0"
      ]
    },
    {
      "id": 286,
      "name": "Revive",
      "deck": "White",
      "side": "hero",
      "timing": "hand",
      "copies": 8,
      "cost": "3☼",
      "text": "Revive a hero who died.\n\nSet the hero's health to their max -5\n\nThe revived hero can not use their action dice this turn, but can use movement dice.",
      "art": "cards/revive.png",
      "raw": [
        "286",
        "hand",
        "1",
        "0",
        "0",
        "Revive",
        "0",
        "White",
        "0",
        "0",
        "",
        "8",
        "Revive a hero who died.\n\nSet the hero's health to their max -5\n\nThe revived hero can not use their action dice this turn, but can use movement dice.",
        "3☼"
      ]
    },
    {
      "id": 170,
      "name": "Rally The Party",
      "deck": "White",
      "side": "hero",
      "timing": "draw",
      "copies": 8,
      "cost": "X☼",
      "text": "Move X heroes to your hero. They choose which space to be placed, they can't be placed through walls.\n\nYou can only move heroes who have already taken their turn.",
      "art": "cards/gather.png",
      "raw": [
        "170",
        "draw",
        "1",
        "1",
        "0",
        "Rally The Party",
        "0",
        "White",
        "0",
        "0",
        "",
        "8",
        "Move X heroes to your hero. They choose which space to be placed, they can't be placed through walls.\n\nYou can only move heroes who have already taken their turn.",
        "X☼"
      ]
    },
    {
      "id": 175,
      "name": "HideOut",
      "deck": "White",
      "side": "hero",
      "timing": "draw",
      "copies": 6,
      "cost": "3☼",
      "text": "Move to the nearest door and enter it.\n\nIf the distance to the nearest door is a tie, you can choose which to go to.",
      "art": "cards/house.png",
      "raw": [
        "175",
        "draw",
        "1",
        "1",
        "0",
        "HideOut",
        "0",
        "White",
        "0",
        "0",
        "",
        "6",
        "Move to the nearest door and enter it.\n\nIf the distance to the nearest door is a tie, you can choose which to go to.",
        "3☼"
      ]
    },
    {
      "id": 192,
      "name": "empty",
      "deck": "White",
      "side": "hero",
      "timing": "draw",
      "copies": 25,
      "cost": "0",
      "text": "You find nothing.",
      "art": "cards/empty.png",
      "raw": [
        "192",
        "draw",
        "1",
        "1",
        "0",
        "empty",
        "0",
        "White",
        "0",
        "0",
        "",
        "25",
        "You find nothing.",
        "0"
      ]
    },
    {
      "id": 196,
      "name": "Distraction",
      "deck": "White",
      "side": "hero",
      "timing": "draw",
      "copies": 10,
      "cost": "1☼",
      "text": "Make a monster or minion move 1 space in any direction\n\nThey can not move through walls or other objects.\n\nYou can not move them in a space that would initiate an attack or combat.",
      "art": "cards/distract.png",
      "raw": [
        "196",
        "draw",
        "1",
        "1",
        "0",
        "Distraction",
        "0",
        "White",
        "0",
        "0",
        "",
        "10",
        "Make a monster or minion move 1 space in any direction\n\nThey can not move through walls or other objects.\n\nYou can not move them in a space that would initiate an attack or combat.",
        "1☼"
      ]
    },
    {
      "id": 285,
      "name": "Counter Spell",
      "deck": "White",
      "side": "hero",
      "timing": "draw",
      "copies": 10,
      "cost": "3☼",
      "text": "Once you use this card, you can negate the effects of any one card used by the monster on their turn.",
      "art": "cards/aid.png",
      "raw": [
        "285",
        "draw",
        "1",
        "1",
        "0",
        "Counter Spell",
        "0",
        "White",
        "0",
        "0",
        "",
        "10",
        "Once you use this card, you can negate the effects of any one card used by the monster on their turn.",
        "3☼"
      ]
    },
    {
      "id": 205,
      "name": "Corrupted Potion",
      "deck": "White",
      "side": "hero",
      "timing": "draw",
      "copies": 11,
      "cost": "0",
      "text": "The monster draws a card instead.",
      "art": "cards/corrupt.png",
      "raw": [
        "205",
        "draw",
        "1",
        "1",
        "0",
        "Corrupted Potion",
        "0",
        "White",
        "0",
        "0",
        "",
        "11",
        "The monster draws a card instead.",
        "0"
      ]
    },
    {
      "id": 219,
      "name": "Brew a Potion",
      "deck": "White",
      "side": "hero",
      "timing": "draw",
      "copies": 10,
      "cost": "X☼",
      "text": "Restore X+2 health to you or a nearby hero.",
      "art": "cards/potion.png",
      "raw": [
        "219",
        "draw",
        "1",
        "1",
        "0",
        "Brew a Potion",
        "0",
        "White",
        "0",
        "0",
        "",
        "10",
        "Restore X+2 health to you or a nearby hero.",
        "X☼"
      ]
    },
    {
      "id": 223,
      "name": "Boots6",
      "deck": "White",
      "side": "hero",
      "timing": "draw",
      "copies": 10,
      "cost": "1☼",
      "text": "Increase the next movement roll by +6 for one turn only.",
      "art": "cards/bootR.png",
      "raw": [
        "223",
        "draw",
        "1",
        "1",
        "0",
        "Boots6",
        "0",
        "White",
        "0",
        "0",
        "",
        "10",
        "Increase the next movement roll by +6 for one turn only.",
        "1☼"
      ]
    },
    {
      "id": 232,
      "name": "Boots4",
      "deck": "White",
      "side": "hero",
      "timing": "draw",
      "copies": 10,
      "cost": "0",
      "text": "Increase the next movement roll by +4 for one turn only.",
      "art": "cards/bootB.png",
      "raw": [
        "232",
        "draw",
        "1",
        "1",
        "0",
        "Boots4",
        "0",
        "White",
        "0",
        "0",
        "",
        "10",
        "Increase the next movement roll by +4 for one turn only.",
        "0"
      ]
    },
    {
      "id": 246,
      "name": "Boots2",
      "deck": "White",
      "side": "hero",
      "timing": "draw",
      "copies": 10,
      "cost": "0",
      "text": "Increase the next movement roll by +2 for one turn only.",
      "art": "cards/bootG.png",
      "raw": [
        "246",
        "draw",
        "1",
        "1",
        "0",
        "Boots2",
        "0",
        "White",
        "0",
        "0",
        "",
        "10",
        "Increase the next movement roll by +2 for one turn only.",
        "0"
      ]
    },
    {
      "id": 255,
      "name": "Aggressive Sprint",
      "deck": "White",
      "side": "hero",
      "timing": "draw",
      "copies": 10,
      "cost": "0",
      "text": "Increase your next movement and your next action roll by +2 for one turn only.",
      "art": "cards/sprint.png",
      "raw": [
        "255",
        "draw",
        "1",
        "1",
        "0",
        "Aggressive Sprint",
        "0",
        "White",
        "0",
        "0",
        "",
        "10",
        "Increase your next movement and your next action roll by +2 for one turn only.",
        "0"
      ]
    }
  ]
};
